version: '3'

services:
  node-api:
    container_name: node-api
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
#    ports:
#      - 8080:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - api-network
    command: .docker/node/entrypoint.sh

  node-api-proxy:
    container_name: node-api-proxy
    image: nginx
    ports:
      - 80:80
    depends_on:
      - node-api
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-network

  node-api-db:
    container_name: node-api-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - api-network

networks:
  api-network:
    name: api-network
    driver: bridge
