version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - api-network
    command: .docker/node/entrypoint.sh

networks:
  api-network:
    name: api-network
    driver: bridge
